title: Tropos Legal Portal
description: Public policies and legal notices for Tropos BV
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Enable navigation
search_enabled: true
heading_anchors: true

# Optional: logo, favicon, nav_order
logo: /assets/images/logo.svg
favicon_ico: /assets/favicon.ico

# Aux links for the upper right navigation
aux_links:
  "Visit our website":
    - "//www.tropos.io"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Google Analytics Tracking
ga_tracking: G-TKW9F957F6
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

markdown: kramdown

callouts:
  warning:
    title: Warning
    color: red